version: "2"

services:

  php:
    image: ${IMAGE_PHP}
    container_name: "${COMPOSE_PROJECT_NAME}_php"
#    depends_on:
#      - mysql
    volumes:
      - ../drupal/:/var/www/html:z
    restart: always
    networks:
      - front

  nginx:
    image: skilldlabs/nginx:1.10.1
    container_name: "${COMPOSE_PROJECT_NAME}_web"
    depends_on:
      - php
    volumes_from:
      - php
    volumes:
      - ./drupal8.conf:/etc/nginx/conf.d/drupal8.conf:z
    restart: always
    networks:
      - front

#  mysql:
#    image: percona:5.7
#    container_name: "${COMPOSE_PROJECT_NAME}_mysql"
#    volumes:
#      - ../mysql:/var/lib/mysql:Z
#    environment:
#      MYSQL_DATABASE: d8
#      MYSQL_USER: d8
#      MYSQL_PASSWORD: d8
#      MYSQL_ROOT_PASSWORD: d8root
#    restart: always
#    networks:
#      - front

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "${IPRANGE}"
